update sync and create repos

diff --git a/bin/repo-sync b/bin/repo-sync
--- a/bin/repo-sync
+++ b/bin/repo-sync
@@ -1,13 +1,31 @@
 #!/bin/sh
 . /root/.pulp/credentials
 
+LOGFILE="/var/log/sync.log"
+
+touch $LOGFILE
+
+function sync_quietly_then_check {
+  pulp-admin rpm repo sync run --repo-id=$1 2>&1 1>$LOGFILE
+  if [[ $? -ne 0 ]] ; then
+    echo "Failed sync: $1"
+  fi
+}
+
 pulp-admin login --username $PULP_USER --password $PULP_PASSWORD
-pulp-admin rpm repo sync run --repo-id=centos-7-base-x86_64-live
-pulp-admin rpm repo sync run --repo-id=centos-7-updates-x86_64-live
-pulp-admin rpm repo sync run --repo-id=centos-6-base-x86_64-live
-pulp-admin rpm repo sync run --repo-id=centos-6-updates-x86_64-live
-pulp-admin rpm repo sync run --repo-id=rhel-6-server-x86_64-live
-pulp-admin rpm repo sync run --repo-id=rhel-6-server-i386-live
-pulp-admin rpm repo sync run --repo-id=rhel-5-server-x86_64-live
-pulp-admin rpm repo sync run --repo-id=rhel-5-server-i386-live
-pulp-admin rpm repo sync run --repo-id=epel-7-x86_64-live
+
+sync_quietly_then_check centos-7-base-x86_64-live
+sync_quietly_then_check centos-7-updates-x86_64-live
+sync_quietly_then_check centos-6-base-x86_64-live
+sync_quietly_then_check centos-6-updates-x86_64-live
+sync_quietly_then_check centos-5-base-x86_64-live
+sync_quietly_then_check centos-5-updates-x86_64-live
+sync_quietly_then_check centos-5.4-base-x86_64-live
+sync_quietly_then_check centos-5.4-updates-x86_64-live
+sync_quietly_then_check rhel-6-server-x86_64-live
+sync_quietly_then_check rhel-6-server-i386-live
+sync_quietly_then_check rhel-5-server-x86_64-live
+sync_quietly_then_check rhel-5-server-i386-live
+sync_quietly_then_check epel-7-x86_64-live
+
+pulp-admin logout
